spring:
    cloud:
        gateway:
            httpclient:
                wiretap: true
            httpserver:
                wiretap: true
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
                        allowedHeaders: "*"
            default-filters:
              #This is to prevent two different cors headers being sent.
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

logging:
    level:
        reactor:
            netty: INFO
        org:
            springframework:
                cloud:
                    gateway: TRACE